name: Publish

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
      - run: npm i
      - run: npx @11ty/eleventy
      - uses: actions/upload-pages-artifact@v3.0.1
